#!/usr/bin/env python3
"""Append one row to the Flutter Web perf-trends history and regenerate the
self-contained dashboard that plots it.

Reads the two things web-perf.yml already produces:
  - perf-report/size-budget.json   (tool/size_budget.sh's machine output)
  - perf-report/lighthouse/        (lhci filesystem upload: manifest.json +
    one report per run; the "representative" run is the median one lhci
    itself picked for the `median-run` assertions in lighthouserc.json)

and writes/updates a JSON array (one object per build) plus an index.html
that embeds that array and draws it with plain <canvas> -- no chart
library, no external service, so the whole trend lives in the git history
of whichever branch these two files are committed to (see
docs/web-performance.md, "Performance history").

Usage:
  record_perf_history.py --size-budget FILE --lighthouse-dir DIR
                          --history-json FILE --dashboard-html FILE
                          --sha SHA --run-url URL [--date ISO8601]
"""
import argparse
import datetime
import json
import os


def load_size_budget(path):
    with open(path) as f:
        budgets = json.load(f)
    by_label = {}
    for b in budgets:
        label = b["label"]
        if "Application JS" in label:
            by_label["js_brotli_kb"] = b["brotliKB"]
        elif "Custom fonts" in label:
            by_label["fonts_brotli_kb"] = b["brotliKB"]
        elif "Renderer (CanvasKit" in label:
            by_label["canvaskit_brotli_kb"] = b["brotliKB"]
        elif "First-load total" in label:
            by_label["total_brotli_kb"] = b["brotliKB"]
    return by_label


def load_lighthouse(lighthouse_dir):
    manifest_path = os.path.join(lighthouse_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        return {}
    with open(manifest_path) as f:
        manifest = json.load(f)
    if not manifest:
        return {}
    entry = next((e for e in manifest if e.get("isRepresentativeRun")), manifest[0])
    result = {}
    summary = entry.get("summary") or {}
    if "performance" in summary:
        result["performance_score"] = round(summary["performance"] * 100, 1)

    json_path = entry.get("jsonPath")
    if json_path:
        if not os.path.isabs(json_path):
            candidate = os.path.join(lighthouse_dir, os.path.basename(json_path))
            json_path = candidate if os.path.exists(candidate) else json_path
        if os.path.exists(json_path):
            with open(json_path) as f:
                report = json.load(f)
            audits = report.get("audits", {})
            fcp = audits.get("first-contentful-paint", {}).get("numericValue")
            lcp = audits.get("largest-contentful-paint", {}).get("numericValue")
            if fcp is not None:
                result["fcp_ms"] = round(fcp, 1)
            if lcp is not None:
                result["lcp_ms"] = round(lcp, 1)
    return result


HISTORY_PLACEHOLDER = "/*__PERF_HISTORY_JSON__*/"


def dashboard_html(history):
    data_json = json.dumps(history)
    template = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Parcello - Flutter Web perf trends</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: system-ui, sans-serif;
    margin: 0;
    padding: 24px;
    background: Canvas;
    color: CanvasText;
  }
  h1 { font-size: 1.3rem; margin: 0 0 4px; }
  p.sub { color: GrayText; margin: 0 0 24px; font-size: 0.9rem; }
  .chart { margin-bottom: 32px; }
  .chart h2 { font-size: 1rem; margin: 0 0 8px; }
  canvas { width: 100%; height: 260px; border: 1px solid color-mix(in srgb, CanvasText 20%, transparent); border-radius: 8px; }
  .empty { color: GrayText; font-style: italic; }
  footer { margin-top: 32px; color: GrayText; font-size: 0.8rem; }
  code { font-size: 0.85em; }
</style>
</head>
<body>
<h1>Flutter Web perf trends</h1>
<p class="sub">One point per successful build on <code>main</code> (see docs/web-performance.md, "Performance history"). Data: <a href="perf-history.json">perf-history.json</a>.</p>
<div id="charts"></div>
<footer>Generated by <code>clients/flutter/tool/record_perf_history.py</code>.</footer>
<script>
const HISTORY = /*__PERF_HISTORY_JSON__*/;

const SERIES = [
  { title: "Lighthouse Performance score", key: "performance_score", unit: "", color: "#2563eb" },
  { title: "First Contentful Paint", key: "fcp_ms", unit: " ms", color: "#7c3aed" },
  { title: "Largest Contentful Paint", key: "lcp_ms", unit: " ms", color: "#db2777" },
  { title: "Application JS (Brotli)", key: "js_brotli_kb", unit: " KB", color: "#059669" },
  { title: "Fonts (Brotli)", key: "fonts_brotli_kb", unit: " KB", color: "#d97706" },
  { title: "CanvasKit renderer (Brotli)", key: "canvaskit_brotli_kb", unit: " KB", color: "#0891b2" },
  { title: "First-load total (Brotli)", key: "total_brotli_kb", unit: " KB", color: "#dc2626" },
];

function drawChart(canvas, points, color, unit) {
  const dpr = window.devicePixelRatio || 1;
  const rect = canvas.getBoundingClientRect();
  canvas.width = rect.width * dpr;
  canvas.height = rect.height * dpr;
  const ctx = canvas.getContext("2d");
  ctx.scale(dpr, dpr);
  const w = rect.width, h = rect.height;
  const pad = { l: 48, r: 12, t: 12, b: 24 };
  const fg = getComputedStyle(document.body).color;
  ctx.clearRect(0, 0, w, h);

  const values = points.map(p => p.v);
  let min = Math.min(...values), max = Math.max(...values);
  if (min === max) { min -= 1; max += 1; }
  const margin = (max - min) * 0.1;
  min -= margin; max += margin;

  const x = i => pad.l + (i / Math.max(points.length - 1, 1)) * (w - pad.l - pad.r);
  const y = v => h - pad.b - ((v - min) / (max - min)) * (h - pad.t - pad.b);

  ctx.strokeStyle = "color-mix(in srgb, " + fg + " 25%, transparent)";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(pad.l, pad.t); ctx.lineTo(pad.l, h - pad.b); ctx.lineTo(w - pad.r, h - pad.b);
  ctx.stroke();

  ctx.fillStyle = fg;
  ctx.font = "11px system-ui, sans-serif";
  ctx.textAlign = "right";
  ctx.textBaseline = "middle";
  ctx.fillText(max.toFixed(1), pad.l - 6, pad.t + 4);
  ctx.fillText(min.toFixed(1), pad.l - 6, h - pad.b - 4);

  ctx.strokeStyle = color;
  ctx.lineWidth = 2;
  ctx.beginPath();
  points.forEach((p, i) => {
    const px = x(i), py = y(p.v);
    if (i === 0) ctx.moveTo(px, py); else ctx.lineTo(px, py);
  });
  ctx.stroke();

  ctx.fillStyle = color;
  points.forEach((p, i) => {
    ctx.beginPath();
    ctx.arc(x(i), y(p.v), 3, 0, Math.PI * 2);
    ctx.fill();
  });

  canvas.onmousemove = (ev) => {
    const bx = ev.offsetX;
    let nearest = 0, best = Infinity;
    points.forEach((p, i) => {
      const d = Math.abs(x(i) - bx);
      if (d < best) { best = d; nearest = i; }
    });
    const p = points[nearest];
    canvas.title = p.date + " (" + p.sha.slice(0, 7) + "): " + p.v + unit;
  };
}

const container = document.getElementById("charts");
if (!HISTORY.length) {
  container.innerHTML = '<p class="empty">No data yet.</p>';
} else {
  SERIES.forEach(s => {
    const points = HISTORY
      .filter(r => r[s.key] !== undefined && r[s.key] !== null)
      .map(r => ({ date: r.date, sha: r.sha, v: r[s.key] }));
    if (!points.length) return;
    const section = document.createElement("div");
    section.className = "chart";
    const latest = points[points.length - 1].v;
    section.innerHTML = '<h2>' + s.title + ' <span style="color:GrayText;font-weight:normal">(latest: ' +
      latest + s.unit + ')</span></h2><canvas></canvas>';
    container.appendChild(section);
    drawChart(section.querySelector("canvas"), points, s.color, s.unit);
  });
}
</script>
</body>
</html>
"""
    return template.replace("/*__PERF_HISTORY_JSON__*/", data_json)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size-budget", required=True)
    ap.add_argument("--lighthouse-dir", required=True)
    ap.add_argument("--history-json", required=True)
    ap.add_argument("--dashboard-html", required=True)
    ap.add_argument("--sha", required=True)
    ap.add_argument("--run-url", required=True)
    ap.add_argument("--date", default=None)
    args = ap.parse_args()

    record = {
        "date": args.date or datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "sha": args.sha,
        "run_url": args.run_url,
    }
    record.update(load_size_budget(args.size_budget))
    record.update(load_lighthouse(args.lighthouse_dir))

    history = []
    if os.path.exists(args.history_json):
        with open(args.history_json) as f:
            history = json.load(f)
    history = [r for r in history if r.get("sha") != args.sha]
    history.append(record)
    history.sort(key=lambda r: r["date"])

    os.makedirs(os.path.dirname(args.history_json) or ".", exist_ok=True)
    with open(args.history_json, "w") as f:
        json.dump(history, f, indent=2)
        f.write("\n")

    os.makedirs(os.path.dirname(args.dashboard_html) or ".", exist_ok=True)
    with open(args.dashboard_html, "w") as f:
        f.write(dashboard_html(history))


if __name__ == "__main__":
    main()
